uint64 omnimagnet # Number associated with omnimagnet configuration
Vector3 current_vec
float64 current_strength # Amps
float64 duration # Seconds
---
bool error # true if an error prevented driver from implementing desired control
string error_desc # Description of failure if error is true