uint64 omnimagnet # Desired omnimagnet ID
Vector3 rotation_vector
float64 rotation_freq # Hz
float64 current_strength # Amps
float64 phase_offset # Degrees
float64 duration # Seconds
---
bool error # true if an error prevented driver from implementing desired control
string error_desc # Description of failure if error is true